from RPA.Excel.Files import Files
from RPA.Tables import Tables


class ExcelGenerator:
    table = Tables()

    def __init__(self):
        self.files = Files()

    """ This method will generate Excel file with all the scraped data. accepting data list generated by 
    get_article_data method as a param """
    def write_to_excel(self, data):
        wb = self.files.create_workbook()
        wb.create_worksheet("data")
        excel_data = self.table.create_table(data)
        self.files.append_rows_to_worksheet(excel_data, header=True)
        self.files.save_workbook("output/output.xlsx")
